# ---- Base Node ----
FROM node:16-buster-slim AS base
# Create app directory
WORKDIR /app

# ---- Dependencies ----
FROM base AS dependencies  
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
# install app dependencies including 'devDependencies'
RUN npm install
#  && yarn add nuxt
# RUN yarn create nuxt-app .

# ---- Copy Files/Build ----
# FROM dependencies AS build
# COPY . /app/
# WORKDIR /app
# EXPOSE 3000
# # Build react/vue/angular bundle static files
# # RUN npm run build

# # --- Release with Alpine ----
# FROM node:16-buster-slim AS release  
# # Create app directory
# WORKDIR /app
# # optional
# # RUN npm -g install serve
# COPY --from=dependencies /app/package.json ./
# # Install app dependencies

# ENV NODE_ENV=production
# RUN npm install --only=production
# COPY --from=build /app ./
#CMD ["serve", "-s", "dist", "-p", "8080"]
# CMD ["node", "server.js"]