# syntax=docker/dockerfile:1
# FROM python:3.9.5-alpine3.13
# FROM python:3.9.5-slim-buster
FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/