# Generated by Django 3.1.4 on 2020-12-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0002_auto_20201225_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
