# Generated by Django 3.1.4 on 2020-12-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0003_auto_20201225_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emote',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ornament',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
