# Generated by Django 3.1.4 on 2020-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0005_auto_20201225_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemeffect',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemset',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemseteffect',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mounteffect',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spellstateeffect',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
