# Generated by Django 3.1.4 on 2020-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0006_auto_20201227_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='food_xp',
            field=models.DecimalField(decimal_places=12, max_digits=25),
        ),
    ]
