# Generated by Django 3.1.4 on 2020-12-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0008_itemprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemprice',
            table='dofus2_item_price',
        ),
    ]
