# Generated by Django 3.1.4 on 2020-12-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0009_auto_20201228_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='category',
            field=models.IntegerField(choices=[(0, 'Average'), (1, 'x1'), (2, 'x10'), (3, 'x100')], default=0),
        ),
    ]
