# Generated by Django 3.1.4 on 2020-12-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dofus2', '0011_auto_20201228_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
